import type { ThemeConfig, ThemeId } from '@/types'

export const themes: Record<ThemeId, ThemeConfig> = {
  mario: {
    id: 'mario',
    bg: 'bg-blue-500',
    headerBg: 'bg-red-600',
    cardBg: 'bg-yellow-400',
    accent: 'bg-red-500',
    accentText: 'text-red-600',
    border: 'border-yellow-500',
    text: 'text-white',
    subtext: 'text-blue-100',
    inputBg: 'bg-yellow-300',
    buttonBg: 'bg-red-500',
    buttonHover: 'hover:bg-red-600',
    fontClass: 'font-bold',
    titleFontClass: 'font-pixel',
    pinStyle: 'pixel',
    icon: '🎮',
    particles: 'mario',
  },
  magia: {
    id: 'magia',
    bg: 'bg-purple-950',
    headerBg: 'bg-purple-900',
    cardBg: 'bg-purple-900',
    accent: 'bg-yellow-500',
    accentText: 'text-yellow-400',
    border: 'border-yellow-600',
    text: 'text-yellow-100',
    subtext: 'text-purple-300',
    inputBg: 'bg-purple-800',
    buttonBg: 'bg-yellow-600',
    buttonHover: 'hover:bg-yellow-500',
    fontClass: 'font-serif',
    titleFontClass: 'font-serif',
    pinStyle: 'magic',
    icon: '🔮',
  },
  cyber: {
    id: 'cyber',
    bg: 'bg-gray-950',
    headerBg: 'bg-gray-900',
    cardBg: 'bg-gray-900',
    accent: 'bg-green-500',
    accentText: 'text-green-400',
    border: 'border-green-700',
    text: 'text-green-400',
    subtext: 'text-green-600',
    inputBg: 'bg-black',
    buttonBg: 'bg-green-700',
    buttonHover: 'hover:bg-green-600',
    fontClass: 'font-mono',
    titleFontClass: 'font-mono',
    pinStyle: 'terminal',
    icon: '💻',
  },
  spazio: {
    id: 'spazio',
    bg: 'bg-slate-950',
    headerBg: 'bg-slate-900',
    cardBg: 'bg-slate-800',
    accent: 'bg-cyan-500',
    accentText: 'text-cyan-400',
    border: 'border-cyan-700',
    text: 'text-cyan-100',
    subtext: 'text-slate-400',
    inputBg: 'bg-slate-700',
    buttonBg: 'bg-cyan-700',
    buttonHover: 'hover:bg-cyan-600',
    fontClass: 'font-tech',
    titleFontClass: 'font-tech',
    pinStyle: 'tech',
    icon: '🚀',
  },
}

export function getTheme(id: string): ThemeConfig {
  return themes[id as ThemeId] ?? themes.mario
}
