import type { ThemeConfig, ThemeId } from '@/types'

export const themes: Record<ThemeId, ThemeConfig> = {
  mario: {
    id: 'mario',
    bg: 'bg-blue-600',
    headerBg: 'bg-red-600/90 backdrop-blur-md',
    cardBg: 'bg-red-900/80 backdrop-blur-md shadow-[0_0_40px_rgba(220,38,38,0.3)]',
    accent: 'bg-yellow-400',
    accentText: 'text-yellow-400',
    border: 'border-yellow-400/50',
    text: 'text-white',
    subtext: 'text-yellow-100',
    inputBg: 'bg-red-950/60',
    inputText: 'text-yellow-300',
    buttonBg: 'bg-gradient-to-r from-yellow-400 to-yellow-500',
    buttonText: 'text-red-950',
    buttonHover: 'hover:brightness-110 hover:shadow-[0_0_20px_rgba(250,204,21,0.6)] transform transition-all',
    fontClass: 'font-bold',
    titleFontClass: 'font-pixel',
    pinStyle: 'pixel',
    icon: '🎮',
    particles: 'mario',
  },
  magia: {
    id: 'magia',
    bg: 'bg-purple-950',
    headerBg: 'bg-purple-900/90 backdrop-blur-md',
    cardBg: 'bg-purple-950/80 backdrop-blur-md shadow-[0_0_40px_rgba(147,51,234,0.4)]',
    accent: 'bg-yellow-500',
    accentText: 'text-yellow-400',
    border: 'border-purple-400/40',
    text: 'text-purple-50',
    subtext: 'text-purple-300',
    inputBg: 'bg-purple-900/60',
    inputText: 'text-yellow-200',
    buttonBg: 'bg-gradient-to-r from-purple-600 to-purple-800',
    buttonText: 'text-yellow-100',
    buttonHover: 'hover:brightness-110 hover:shadow-[0_0_20px_rgba(168,85,247,0.6)] transform transition-all',
    fontClass: 'font-serif',
    titleFontClass: 'font-serif',
    pinStyle: 'magic',
    icon: '🔮',
  },
  cyber: {
    id: 'cyber',
    bg: 'bg-gray-950',
    headerBg: 'bg-black/90 backdrop-blur-md',
    cardBg: 'bg-gray-950/80 backdrop-blur-md shadow-[0_0_40px_rgba(34,197,94,0.2)]',
    accent: 'bg-green-500',
    accentText: 'text-green-400',
    border: 'border-green-500/40',
    text: 'text-green-400',
    subtext: 'text-green-600',
    inputBg: 'bg-black/80',
    inputText: 'text-green-300',
    buttonBg: 'bg-gradient-to-r from-green-800 to-green-950',
    buttonText: 'text-green-400',
    buttonHover: 'hover:brightness-110 hover:shadow-[0_0_20px_rgba(34,197,94,0.4)] transform transition-all',
    fontClass: 'font-mono',
    titleFontClass: 'font-mono',
    pinStyle: 'terminal',
    icon: '💻',
  },
  spazio: {
    id: 'spazio',
    bg: 'bg-slate-950',
    headerBg: 'bg-slate-900/90 backdrop-blur-md',
    cardBg: 'bg-slate-900/80 backdrop-blur-md shadow-[0_0_40px_rgba(6,182,212,0.3)]',
    accent: 'bg-cyan-500',
    accentText: 'text-cyan-400',
    border: 'border-cyan-500/40',
    text: 'text-cyan-50',
    subtext: 'text-cyan-300',
    inputBg: 'bg-slate-800/60',
    inputText: 'text-cyan-200',
    buttonBg: 'bg-gradient-to-r from-cyan-700 to-blue-800',
    buttonText: 'text-white',
    buttonHover: 'hover:brightness-110 hover:shadow-[0_0_20px_rgba(6,182,212,0.5)] transform transition-all',
    fontClass: 'font-tech',
    titleFontClass: 'font-tech',
    pinStyle: 'tech',
    icon: '🚀',
  },
}

export function getTheme(id: string): ThemeConfig {
  return themes[id as ThemeId] ?? themes.mario
}
